# Project: DoA
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = mainDoaVariosMicrofonesCorrelacaoCruzada.o decompoeCovMatrixEmAutovetoresEAutovalores.o calculaMatrizCovariancia.o
LINKOBJ  = mainDoaVariosMicrofonesCorrelacaoCruzada.o decompoeCovMatrixEmAutovetoresEAutovalores.o calculaMatrizCovariancia.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = DoA.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

mainDoaVariosMicrofonesCorrelacaoCruzada.o: mainDoaVariosMicrofonesCorrelacaoCruzada.c
	$(CC) -c mainDoaVariosMicrofonesCorrelacaoCruzada.c -o mainDoaVariosMicrofonesCorrelacaoCruzada.o $(CFLAGS)

decompoeCovMatrixEmAutovetoresEAutovalores.o: decompoeCovMatrixEmAutovetoresEAutovalores.c
	$(CC) -c decompoeCovMatrixEmAutovetoresEAutovalores.c -o decompoeCovMatrixEmAutovetoresEAutovalores.o $(CFLAGS)

calculaMatrizCovariancia.o: calculaMatrizCovariancia.c
	$(CC) -c calculaMatrizCovariancia.c -o calculaMatrizCovariancia.o $(CFLAGS)
